### ISSUE TITLE
yo reactor not found

### ISSUE THREAD

**Issue by radjivF** [willmendesneto/generator-reactor#2]
![screen shot 2016-04-28 at 4 35 40 pm](https://cloud.githubusercontent.com/assets/5714138/14877318/4f96d6ee-0d5f-11e6-85c7-7b086e1a9e3d.png)

**Comment by willmendesneto** [comment]
@radjivC Could you add here the print of this command, please?

`node -v && npm -v && npm list -g --depth=0`

**Comment by radjivF** [comment]
I've fixed it a while ago, but I dont remember how. I guess it's all good. Thx @willmendesneto

**Comment by willmendesneto** [comment]
It was a pleasure. Sorry for delay in my reply.
